const fs = require('fs');
const path = require('path');

const readmePath = path.join(__dirname, '../README.md');
const docsPath = path.join(__dirname, '../docs/getting-started.md');
const readmeContent = fs.readFileSync(readmePath, 'utf8');

// Strip the first few lines which usually contain the logo and badges for GitHub
// We assume the actual content starts after the first horizontal rule (---) or after some initial lines.
// Adjust this logic based on the actual README structure.
// Strategy: Look for the first "Installation" or major header, or just strip the first N lines.
// Better Strategy: Find the first "## " or similar structure that isn't the title, OR keep it simple.

// Let's remove the first image/logo section if it exists
// Regex to remove the header section up to the first 'Initialization' or 'Installation' code block or header.

// Based on the user's README, it has a logo and some badges.
// <img src="..." ... />
// ... badges ...
// See full documentation [here]...
// ---
// <br>
// Installation:

// We want to remove everything up to "Installation:" or the first code block.
// Or we can just remove lines until we hit "Installation:"

const lines = readmeContent.split('\n');
let startLineIndex = 0;

// Simple heuristic: Skip until we see "Installation:"
for (let i = 0; i < lines.length; i++) {
    if (lines[i].includes('Installation:')) {
        startLineIndex = i;
        break;
    }
}

// Reassemble content
const cleanContent = lines.slice(startLineIndex).join('\n');

const finalContent = `---
title: Getting Started
---

<!--
    ⚠️ WARNING: DO NOT EDIT THIS FILE MANUALLY ⚠️

    This file is strictly auto-generated from README.md.
    Any changes made here will be overwritten by the next build.
    To make changes, edit the README.md file in the root directory.
-->

# Getting Started

${cleanContent}
`;

fs.writeFileSync(docsPath, finalContent);
console.log('Synced README.md to docs/getting-started.md');
