on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Coverage tests

jobs:

  coverage-tests:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-replica-set: rs0

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - run: npm ci

      - name: npm run test:coverage
        run: npm run test:coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: './reports/coverage/lcov.info'
