name: Stryker - Mutation testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm run test:stryker
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
