name: Stryker - Mutation testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  mutation-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-replica-set: rs0
      - run: npm ci
      - run: npm run test:stryker
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
